version: '3.8'

services:
  sveltekit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5757:3000"
    depends_on:
      - websocket

  websocket:
    build:
      context: .
      dockerfile: Dockerfile.websocket
    ports:
      - "4040:4000"