version: '3.8'

services:
  sveltekit:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - websocket

  websocket:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "4000:4000"