version: '3.8'

services:
  new_mailer:
    container_name: new_mailer
    build:
      context: .
    env_file:
      - .env
    ports:
      - 5173:5173
    volumes:
      - /app/node_modules
      - .:/app